### ISSUE TITLE
tutorial number2

### ISSUE THREAD

**Issue by hualde** [ros-industrial-consortium/descartes_tutorials#16]
Hello community!
One question, in the tutorial number 2, there is a section in cpp code wich i dontt understand, it`s the part where it populates the pose matrix, i understand how to obtain "pos" and "norm" vectors, but why the rest of the colums of pose matrix are:

      Eigen::Vector3d temp_x = (-1 * pos).normalized();
      Eigen::Vector3d y_axis = (norm.cross(temp_x)).normalized();
      Eigen::Vector3d x_axis = (y_axis.cross(norm)).normalized();
      Eigen::Isometry3d pose;
      pose.matrix().col(0).head<3>() = x_axis;
      pose.matrix().col(1).head<3>() = y_axis;
      pose.matrix().col(2).head<3>() = norm;
      pose.matrix().col(3).head<3>() = pos;

If someone can give me some explanation,maybe it's a mathematical normal procedure or something... 
Thank you everyone

**Comment by JeroenDM** [comment]
(I did not write the code, but this is how I understand it.)

The code creates an x-axis and a y-axis perpendicular to the z-axis (which is oriented along the `norm` vector). Because the exact direction of the x and y axes is not important, they are created at random, but perpendicular with `norm`. 

`pos` seems to be used to create a random vector `temp_x`. The [cross product](https://en.wikipedia.org/wiki/Cross_product) of two vectors gives a vector perpendicular on both vectors, and thus (`norm "cross" temp_x`) will generate a vector perpendicular to `norm`.

Similarly, (`y_axis "cross" norm`) creates a vector perpendicular to `y_axis` and `norm`, representing the `x_axis`.

**Comment by hualde** [comment]
Thank you very much Jeoren!!!
I like your explanation
I owe you a beer!!!
Thank you again

**Comment by JeroenDM** [comment]
I'm glad I could help :) Could you close the issue maybe? @hualde  I do not have the rights to do it.

**Comment by JeroenDM** [comment]
That was fast :)
